### ISSUE TITLE
不能保存

### ISSUE THREAD

**Issue by lcqbug** [developerHaoz/DoodleView#1]
我看了一下, 保存  有toast, 实际目录下并没有生成png.  配置文件也没有相关的权限, 加上也没有..

**Comment by zktzktzkt** [comment]
那是创建文件的过程有问题，按照我这么写

` 
public String saveBitmap(DoodleView doodleView) {
        String dirPth = getContext().getExternalCacheDir().getPath() + "/doodleview/";

        File dir = new File(dirPth);
        if (!dir.exists()) {
            boolean newDir = dir.mkdirs();
            Log.e("创建是否成功？", newDir + "");
        }

        File file = new File(dir, System.currentTimeMillis() + ".png");
        try {
            if (!file.exists()) {
                file.createNewFile();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        //保存bit为png
        savePicByPNG(doodleView.getBitmap(), file.getPath());
        return file.getPath();
    }`

**Comment by afunnyrainman** [comment]
那是因为大佬的DEMO没有申请权限。
