### ISSUE TITLE
第二次进入，画板怎么加载上一次绘制的图呢。

### ISSUE THREAD

**Issue by jinlinupup** [developerHaoz/DoodleView#4]
我这么写是没有效果的。。
canvas = Canvas(getDiskBitmap(intent.getStringExtra("imageUrl")))
mDoodleView.draw(canvas)
-------------------------
private fun getDiskBitmap(pathString: String): Bitmap? {
        var bitmap: Bitmap? = null
        try {
            val file = File(pathString)
            if (file.exists()) {
                bitmap = BitmapFactory.decodeFile(pathString).copy(Bitmap.Config.ARGB_8888, true);
            }
        } catch (e: Exception) {
            // TODO: handle exception
        }

        return bitmap
    }

**Comment by jinlinupup** [comment]
我获取到了iamgeUrl并打印了出来。

**Comment by developerHaoz** [comment]
![image](https://user-images.githubusercontent.com/20362200/34865942-a30b39fe-f7b5-11e7-94a1-61d17273d062.png)

可以获取上次图的 Action，然后重新在 Canvas 上面画一遍
